/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import org.example.Clases.Audio

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun main() {
}
